charmbracelet/gum

input/command.go
input/options.go

Fixes #28
Adds `--password` flag to `gum input` to mask characters while typing for
passwords.

Add `--password` option for masked input

---

.github/workflows/lint-soft.yml
.github/workflows/lint.yml
.golangci-soft.yml
.golangci.yml
choose/choose.go
choose/options.go
completion/bash.go
completion/command.go
completion/fish.go
completion/zsh.go
confirm/options.go
filter/command.go
filter/filter.go
filter/options.go
format/command.go
format/formats.go
input/options.go
internal/files/files.go
main.go
spin/options.go
spin/spin.go
write/options.go

Adds soft- & hard-enforced linter configs and GitHub workflows. Fixed all the linter errors I encountered while I was at it. Please review, in particular the template/renderer error handling. I also noticed there's a bit of unused code, which we may be able to remove (unless it's used by kong's reflection?).

Add soft & hard linter configs & workflows

---

man/command.go

Sets the right man pages description without any escape sequences and styling.

fix: man pages binary description

---

README.md

Pre-formats the `gh pr list` output a bit.

chore: nicer PR example in README

---

choose/choose.go

Fixes #85 when running `gum choose` with limit > 1
- Add <kbd>a</kbd> keybinding to select all items in `gum choose`
- Add <kbd>A</kbd> keybinding to deselect all items in `gum choose`
https://user-images.githubusercontent.com/6196971/182436274-ee8f1099-4c95-485b-b7cf-3f49a4503f8c.mov

feat: select/deselect all items in gum choose with a/A

---

choose/options.go
confirm/options.go
filter/options.go
input/options.go
spin/options.go
style/options.go
write/options.go

- Allow most aspects of gum (mainly theming) to be configured by default
through `ENV_VARS` and be overridden by `--flags`
Generally the environment variables follow the following scheme:
1. `GUM_`
2. `<COMMAND>_`
3. `FLAG` (replace `-` and `.` with `_`)
For example, `gum filter` can be customized by default through the following flags:
```bash
export GUM_FILTER_INDICATOR="*"
export GUM_FILTER_INDICATOR_FOREGROUND=1
export GUM_FILTER_PROMPT="→"
export GUM_FILTER_PROMPT_FOREGROUND=1
gum filter
```

Environment Variable Configuration

---

README.md
write/write.go

Fixes: N/A
- added some comments to `write.go` clarifying how to complete text entry 
- updated the `README.md` to clarify how to complete (or exit) a 'write'

added clarity on completing a 'write'

---

.github/workflows/goreleaser.yml

gum-bin was deleted from AUR because it is now on main, so we should not push it again.
https://aur.archlinux.org/packages?O=0&K=gum-bin

fix: disable aur publish

---

confirm/command.go
confirm/confirm.go
confirm/options.go

Fixes #103 
Closes #106 
- `--timeout` flag that takes a `time.Duration` for timing out the confirm.

add timeout on confirm options & messages

---

examples/filter-key-value.sh

- Fixing a minor warning ```filter-key-value.sh: line 12: warning: here-document at line 8 delimited by end-of-file (wanted `END')```

docs: fix a warning in the filter-key-value example

---

choose/choose.go

Fixes https://github.com/charmbracelet/gum/issues/117
- <kbd>G</kbd> last element / <kbd>g</kbd> first element
- When on first element, up goes to the last element (wrap)
- When on last element, down goes to the first element (wrap)

Wrap around choose list

---

choose/choose.go

Fixes #135 
- when pressing "a", it actually checks the number of left selections based on the limit, as opposed to select all items in the list

fix(choose): wrong "a" behavior

---

choose/options.go
filter/command.go
filter/filter.go
filter/options.go

fix #25
This PR adds the support to multiple selections in `filter` command, more or less like it already happens in `choose`.
When more than one selection is allowed, it is possible to mark/unmark a given number of items by pressing `tab`.
If the number of allowed selections is 1, there is no need to first mark the selection, pressing enter will directly print the selection under the cursor (again, like in `choose`).
- introduction of flags/Options similar to what is offered by `choose`:
- `--limit`: set the number of allowed selections (default to 1)
- `--no-limit`: allows any number of selections, overriding limit
- `--selected-prefix`: character(s) that mark selected items
- `--selected-prefix.foreground`: style for the component mentioned above
- `--unselected-prefix`: character(s) …

feat(filter): added multiple selections

---

.gitignore
flake.lock
flake.nix

This is a really simple pull request that adds 2 files `flake.nix` and `flake.lock`. This just makes it easier for people using Nix to get the latest version.
I also added a line to the .gitignore that ignores the default output directory (symlink) when building with nix. 
I would only need to update these files if the dependencies change in the `go.mod` file, but I am happy to maintain it.

added nix flake

---

README.md

I found a description of `gum write` in README that differs from the implementation, so I propose a correction.
https://github.com/charmbracelet/gum/blob/5993a7b4907562d004546561852e7674c7e6d220/write/write.go#L33-L40
↓README
```
`CTRL+D` is used to complete text entry. `CTRL+C` and `esc` will cancel.
```
- [README.md `write`](https://github.com/charmbracelet/gum/tree/5993a7b4907562d004546561852e7674c7e6d220#write)

docs: fix `write` key description

---

default.nix
flake.lock
flake.nix

Fixes #...
The hash was out of date in the nix flake. I went to update it and went ahead and made some other basic improvements in the flake.
1. [flake-utils](https://github.com/numtide/flake-utils) is a commonly used nix library which makes it easier to build flakes which target all the default systems supported by Hydra. 
2. Adding an Overlay allows nix users to more quickly merge `gum` into their local nixpkgs. 
- Updates the vendor hash in the Nix Flake
- Uses flake-utils to support more systems in Nix
- Adds a NIx overlay.

Updates hash and adds overlay to flake

---

filter/filter.go

resolves: #165 
Handle <kbd>shift+tab</kbd> for `gum filter` command by toggling the selection and going up by one line.

feat: use `shift+tab` to toggle selection and move up

---

spin/command.go
spin/options.go
spin/spin.go

Sometimes it is nice to spin to the right side of the title, not the left, so add a --location option to pick the left or right side.  The default remains "left".
New option is:
--location="left|right"
and the environment variable GUM_SPIN_LOCATION can also be used.

feat: add location to spin

---

confirm/confirm.go

This change will hide the normally "No" button when the text is empty. In most cases, this will serve as an acknowledgement and the affirmative message would likely change.
This seems to be better than displaying an empty button.
Resolves #145

fix(confirm): an empty --negative will not be displayed

---

filter/command.go
filter/filter.go
filter/options.go

resolves: #114 
Add `--reverse` flag to `gum filter` command to display the list in reverse direction similar to the default layout for `fzf`

feat(filter): add reverse layout

---

filter/filter.go

We don't need to style each character individually, buffer them and flush before highlights. Greatly improves performance when styling thousands of items after each cursor movement.

perf: speed up filter rendering

---

README.md

Fixes #183 
- Replace `.text` with `.txt`

Change `.text` to `.txt` in README

---

file/command.go

Fixes #203
Allow only `Inline` styles for gum directories and files.

Inline gum file styles

---

filter/command.go
filter/filter.go
filter/options.go

Fixes #50 
Added the `--exact` flag to perform an exact filter (not fuzzy).
To highlight the correct letters I had to override the ones matched originally, and also I had to sort the slice again to avoid the "shuffling" of some elements that were ordered with the fuzzy ranking algorithm.

feat(filter): added `--exact` for exact matches

---

choose/command.go

**Rationale:** If the number of selected options in `--selected` flag is greater than the limit, the last `n` options are selected where `n` is the limit.
Fixes #...
Throw an error if the number of selected options are greater than the specified limit

fix(choose): error if selected options > limit

---

README.md

Use the recommended keyrings path /etc/apt/keyrings
Per: https://manpages.debian.org/unstable/apt/apt-key.8.en.html#DEPRECATION
Fixes: https://github.com/charmbracelet/gum/issues/208
Fixes: https://github.com/charmbracelet/gum/pull/209

docs: apt-key deprecation

---

format/command.go
format/formats.go
format/options.go

Add `--theme` option for customizing Glamour theme used in `gum format`.
The `--theme` can be either a file path or a standard style such as:
* `auto`
* `dark`
* `light`
* `notty`
* `ascii`
* `dracula`
* `pink` (default)

feat: allow customization of glamour theme

---

README.md

Makes the README instructions even more crowded, but hey, gum on Android?!

docs: add Alpine & termux install instructions

---

table/command.go

- `gum table` outputs proper CSV
Before:
After:
Before:
After:

fix(table): output proper CSV for the selected row

---

filter/command.go
filter/options.go

Small enhancement to the filter to allow a non matching filter to be a valid 
result. 
New Option --no-strict to take filter string if no match was found

feature(choose): Adding option to use non-matching filter as result

---

pager/command.go
pager/options.go
pager/pager.go

Partially implements #246
Adds a `--soft-wrap` option to the `gum pager` command. This will simply wrap lines to the next line in the pager.
Before:
After:
Without line numbers:

feat(pager): add --soft-wrap option to gum pager

---

confirm/command.go
confirm/confirm.go

Fixes #230
- Adds exit 130 to <kbd>ctrl+c</kbd> and <kbd>esc</kbd>

feat: ctrl+c / esc aborts action

---

choose/choose.go
choose/command.go
choose/options.go

resolves: #128 
Add flag `--keep-order` for `gum choose` to maintain the order of selection and print it in the correct order at the end.

feat(choose): keep order of selected items

---

go.mod

Fixes errors when building with go versions below v1.17
```bash
$ go version
go version go1.16 darwin/arm64
$ go build
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall.go:83:16: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_darwin.go:95:8: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
```
- `go mod edit -go=1.17`
- `go mod tidy`

build: update go version to 1.17

---

choose/choose.go
filter/filter.go

feat: add `ctrl+@`(`ctrl+space`) keybinding for `choose` and `filter`

---

confirm/command.go
confirm/confirm.go

Fixes #142 
- Change timeout to show on correct prompt (not only on `exit code 1`)
- Fix timeout to not enforce user options to `exit code 1`
Demo for 3 commands:

fix(prompt): fix default selection of prompt, timer and exit code

---

examples/commit.sh

I found out that I had to [add these 3 lines to my `commit` script](https://github.com/GeekMasher/.dotfiles/blob/main/dev/.local/commit) using Gum to make sure if I didn't commit anything I would be prompted if I wanted to include all of the unstaged files.
The big issue with this snippet is that it uses `grep` and `awk` so if a user doesn't have these of their system, it would fail.
I don't know if there is a better way to do this so I'm leaving it like this.
- Added check to commit example in the case of no staged commits

Add staged file check for commit example

---

table/command.go

Fixes #294
- Removed the inheritance function because when setting the selected style it would not allow changes to already set values. The default colour remains unchanged, and now it's the user's choice whether the selected text should be bold or not.
This can also be fixed by removing the setter of the foreground colour on this [line](https://github.com/charmbracelet/bubbles/blob/1ca90b3c942b5833c53a6fdfef78cd1fddfe6025/table/table.go#L100) in the bubbles project.

fix: table ignores foreground color set by the user

---

filter/command.go

Fixes #292
- Added a switch to check for the combination of the two flags
- Kept the original behaviour of using fuzzy if the --no-fuzzy flag isn't present

fix: for using --value in combination w/ --no-fuzzy

---

pager/command.go
write/command.go

Fixes #297
- Removes backspaces, including the character before it, using a regex. The problem stems from when setting the variable and calling the pager, you get the man pages in their nroff format. Which means that it includes ^H chars, and I suspect that hinders bubbletea from calculating the width correctly.

removed bksp from stdin

---

file/command.go
file/file.go

Fixes #315
- Make escape also quit `file`
- Change the returning error code to 130
I tried to make the behaviour as similar as the one from `filter`/`chose`.

fix: added esc to keys and changed error code to 130

---

README.md

Fixes #312
- Moves the `esc` over to the cancel option together with CTRL+c, so it reflects the current behaviour of the program.

fix: correct wrong key combination for gum write in README.md

---

filter/command.go
filter/filter.go
filter/options.go

Fixes nothing, this is a feature I wanted to have access to in `gum`.
Before, only `GUM_FILTER_TEXT_*` could be styled, this meant every line's text would look the same, even the one with the cursor on:
This PR provides a way to style `gum filter`'s cursor text through `GUM_FILTER_CURSOR_TEXT_*` environment variables as such:
I tried to stick to your naming conventions, feel free to rename `CURSOR_TEXT` if you feel like it doesn't match the rest of the project.
Thanks for making `gum`, I really enjoy the added interactivity it brings to shell scripts!

feat(filter): add cursor text line styling

---

spin/command.go
spin/options.go
spin/spin.go

Fixes #...
Timeout on Spin Command

feat: Timeout for Spin Command

---

format/formats.go
main.go

This will allow users to set `NO_COLOR` and `CLICOLOR_FORCE` when they need to override the detected values.

Switch to termenv.EnvColorProfile()

---

spin/command.go

The isTTY check is inverted in the --show-output option for spin, so no output is shown anymore.  Fix this by correctly checking if we are a tty or not.

spin: fix isTTY check

---

write/write.go

Change ESC from aborting to successful quitting.
'vi' users press ESC as an uncontrollable tick, making using 'gum write' painful when all their work is lost.
I'm floating this as an idea.
I could add a non-zero exit code, mostly preserving the current behavior.  If I did that, ctrl-c should also return the text.
If we standardized the exit code, we could apply it to #286.
- ESC now indicates a normal exit (like pressing CTRL+D).

feat(write): ESC should be successful

---

input/command.go

Currently, `gum input` reads from stdin even if we set a value with the `--value` flag. This can cause some issues if we are piping a script into a shell (`$ cat script.sh | bash`) as seen in #447.
- If the `--value` is being used `gum input` would not read from stdin.

fix(input): Avoid reading from stdin if `--value` is being used

---

choose/command.go
choose/options.go
filter/command.go
filter/options.go
format/formats.go
main.go

Fixes #396 
- Add `--select-if-one` to `choose`, returns the only option if only one option is given
- Add `--select-if-one` to `filter`, returns the only option if only one option is given

Add `--select-if-one` flag to `choose`/`filter`.

---

choose/command.go
confirm/command.go
file/command.go
filter/command.go
input/command.go
log/options.go
main.go
pager/command.go
spin/command.go
style/command.go
style/lipgloss.go
style/options.go
table/command.go
write/command.go

Prevents style flags from leaking through when a user makes an error in the usage.
For example:
```
gum write --help
```
using the `--help` flag produces a different usage than the user making an error with the flags.
```
gum write --error
```
This is because we perform the hiding of the flags on `BeforeReset` which is called for the help flag but not on an error.
The downside of this approach is that we must duplicate the style struct so that we can maintain a fully hidden embeddable struct while also having a non-hidden struct so the style command has proper usage / help / errors.
This can be resolve once the following issue is implemented:
https://github.com/alecthomas/kong/issues/316

Hide Style Flags consistently

---

spin/command.go

Fixes the `--show-output` flag not piping output.
Fixes the `--show-output` flag not showing live output.

(fix): ShowOutput flag displays in realtime

---

choose/command.go
filter/command.go

This matches how choose works normally when there are more than
one option.

Add newline printing to --select-if-one

---

choose/command.go
filter/command.go

For some reason it wasn't printing to stdout (and I could repro that
bug even on versions before I added the newline). It was only showing
up on other streams in the shell (error stream probably), not getting
sent into pipes.
I changed it to fmt.Println.
As for the ansi-stripping that was in `filter`, LMK if that's what you
prefer and I'll add it to `choose` too. I just wanted them to match.

fix: Make --select-if-one print to stdout

---

spin/spin.go

Fixes the `--show-output` flag from not working if the program is piped and ended by timeout (`--timeout`)
- Stores output buffer within the model once the timeout is procced

fix(Spin): Output Pipes if Timeout Occurs

---

README.md

The `gum log --help` output for `--time` option says
```
-t, --time=""             The time format to use (kitchen, layout, ansic, rfc822, etc...)
```
with no indication of what `etc...` means. This is probably inferred for proficient Go programmers, but not for everyone else.
This commit makes it clearer which options are supported by `--time` by linking the README to [the appropriate spot](https://pkg.go.dev/time#pkg-constants) in the docs for the `time` library.

Add example and help for gum log --time option to README

---

.goreleaser.yml

gum conflicts with another tool, even if it is in our own bucket, this still makes it difficult to install.
the official scoop for gum is also called charm-gum, so I think this should work better.
refs https://github.com/charmbracelet/scoop-bucket/pull/7

build: rename scoop to charm-gum

---

spin/command.go
spin/options.go
spin/spin.go

This is #440 but rebased so it can be merged easily. Thanks @elliotcourant for making the actual changes!
> This makes it so that if the `--show-error` flag is provided then the full output of the command will be printed if the command fails. This kind of works in conjuncture with `--show-output` in that if the command succeeds only STDOUT is pushed. If the command fails both `STDOUT` and `STDERR` are pushed.
> 
> This builds off of #371
> 
> Resolves #55
> 
> Fixes #55
> 
> ### Changes
> * Adds support for a `--show-error` flag for the spinner command.
> 
> ### Examples
> ```shell
> gum spin -s minidot --show-error -- bash -c "sleep 1 && echo 'you can see me if the command fails' && exit 1"
> # you can see me if the command fails
> # exit status 1
> ```
> 
> ```shell
> gum spin -s …
```

feat(spin): Add support for --show-error for the spinner. (rebase #440)

---

log/command.go

In the go 1.21 required by the project, these constants are already built-in in the standard library. So we can replace it and make code more elegant

Replace custom strings with constants from the standard library

---

pager/pager.go

Since `choose` also supports Home/End for navigation in https://github.com/charmbracelet/gum/issues/393.
It would be nice if `pager` can do the same.

Support using the Home/End keys in pager

---

default.nix
flake.lock
flake.nix

I noticed that all nix related files are 2 years old, so I've created this PR to address this issue. Otherwise I would suggest to remove the files and refer to Nixpkgs instead. (: 
- Changed Nixpkgs to the unstable branch to avoid having to update at each release.
- Updated the flake.lock accordingly.
- Add the ldflags to the default.nix file.

chore: update nix

---

choose/command.go
filter/command.go
internal/stdin/stdin.go
style/command.go

Fixes #573
- When receiving inputs via stdin trim the trailing newline.
- Removed trimsuffix from other commands where stdin was read.

fix(stdin): add trim of trailing newline

---

README.md
man/command.go

I added them in little toggly things to keep the installation instructions section short.

chore(readme): add repo installation instructions for DEBs and RPMs

---

choose/command.go
choose/options.go

Fixes #530
- Use huh to implement custom `gum choose` key and value.

Add key/value feature for `gum choose` (#530)

---

choose/command.go
choose/options.go

Reverts charmbracelet/gum#598 due to a typo. We can fix the typo and re-add this, but after the next release which is purely a bugfix release.

revert: "add key/value feature for `gum choose` (#530)"

---

README.md

`gum` is available and seems to work in [Flox](https://flox.dev/docs/) today.
Since Flox is closely related to Nix, it made sense to me to add it below the existing Nix install instructions. 😊
- Add Flox to the list of installation options in `README.md`

Add flox as an installation method

---

filter/filter.go
timeout/options.go

Fixes nil
- Removes explicitly defined max functions from filter and timeout because they are a native part of Go since 1.21.

chore: remove explicitly defined max functions

---

choose/command.go
go.mod
go.sum

needs https://github.com/charmbracelet/huh/pull/325
closes https://github.com/charmbracelet/gum/issues/550

fix: select all keybinding

---

choose/options.go
file/options.go
table/options.go

refs #634
closes https://github.com/charmbracelet/gum/issues/554

fix: height 0 by default

---

confirm/command.go
confirm/command_test.go

Fixes #698.
Relevant excerpts from `gum confirm --help`
```console
Usage: gum confirm [<prompt>] [flags]
Ask a user to confirm an action
Arguments:
[<prompt>]    Prompt to display.
Flags:
--default              Default confirmation action
--timeout=0            Timeout until confirm returns selected value or default if provided ($GUM_CONFIRM_TIMEOUT)
```
- Chains a `.WithTimeout(o.Timeout)` in the `confirm` command's `huh.NewForm()` chain under `confirm.Run()`
- Adds an `errIsValidTimeout(error) bool` method to `confirm.Options` to facilitate safely ignoring the timeout error returned in the course of the `Run()` context expiring due to timeout
- Adds unit tests for `errIsValidTimeout`
Note that five seconds elapse here before `timeout` kills `gum`, returning a nonzero exit code.
```vhs …
```

fix(confirm) `--timeout` was ignored, now works as documented

---

choose/command.go

Huh returns a `ErrTimeout` on timeout error and we need to catch that.
Fixes: https://github.com/charmbracelet/gum/pull/618
EDIT:
Related: https://github.com/charmbracelet/gum/pull/633

fix: catch huh timeout error

---

spin/spin.go

We don't need to check for isatty, always store the output to the designated buffer.
Fixes: https://github.com/charmbracelet/gum/issues/607

fix(spin): indenting lines when command is piped

---

table/command.go

fix(table): only set height if > 0

---

default.nix

- changed src hash to make main branch build through nix 
```
❯ nix develop
error: hash mismatch in fixed-output derivation '/nix/store/xcrnrbab9zgdzyq67xp2fr3cmws5g37s-gum-0.14.0-go-modules.drv':
specified: sha256-gDDaKrwlrJyyDzgyGf9iP/XPnOAwpkvIyzCXobXrlF4=
got:    sha256-UNBDVIz2VEizkhelCjadkzd2S2yTYXecTFUpCf+XtxY=
error: 1 dependencies of derivation '/nix/store/frz0ik8fcnsvkmn2kynlyxdfy4c8dk73-gum-0.14.0-env.drv' failed to build
```

chore(nix): update src hash

---

filter/command.go
filter/filter.go
filter/options.go

Fixes #695
- `--no-strict` was erroring as non-existent option
- when `--no-strict`, we should actually create a "fake" option with whatever the user is typing

fix(filter): --no-strict not working, also weird behavior

---

choose/choose.go
choose/command.go
filter/command.go
filter/filter.go
filter/options.go

Minor things. Some of these existed prior to v0.14.0.

reverting huh: small fixes and improvements

---

README.md

A tmux session name could contain a space. Quote the variable to avoid
the session name being split on spaces.
- Update tmux session picker example in README to allow for session names which contain spaces

Quote tmux session name in code sample

---

choose/choose.go
choose/command.go
choose/options.go
confirm/command.go
confirm/confirm.go
file/command.go
file/file.go
file/options.go
filter/command.go
filter/filter.go
filter/options.go
go.mod
go.sum
input/command.go
input/input.go
input/options.go
internal/exit/exit.go
main.go
pager/command.go
pager/pager.go
spin/command.go
spin/spin.go
write/command.go
write/options.go
write/write.go

refactor: removing huh as a dep

---

filter/command.go
filter/filter.go
input/command.go
pager/command.go
pager/pager.go

this makes input, write, pager, and filter, properly handle focus/blur events

feat: handle focus/blur events

---

internal/stdin/stdin.go

most programs should not give output with ansi sequences to a pipe, but as some of them do, this will strip them out.
closes #188

fix: strip ansi sequences from stdin

---

choose/command.go
filter/command.go
format/command.go
input/command.go
internal/stdin/stdin.go
style/command.go
write/command.go

it makes sense to strip everywhere else, but I think the pager is the exception.
closes #509

fix(pager): do not strip ansi sequences

---

write/command.go
write/options.go

- it makes no sense to me to have 400 as limit?
- textarea default max height is 99, we should probably set it to 0
closes https://github.com/charmbracelet/gum/issues/666

fix(write): max height, max chars

---

table/command.go

I'm not sure about this, as it might be slow in big tables...
This will go through all rows, calculate their widths, and set it as the column width if none was provided with `-w`.
```bash
echo -e "a,b\naaaaaaaaaaaaaaaaaaaaaaa,bbbbbbbbbbbbbbbb" | gum table
```
```
a  b
…  …
```
```bash
echo -e "a,b\naaaaaaaaaaaaaaaaaaaaaaa,bbbbbbbbbbbbbbbb" | gum table
```
```
a                        b
aaaaaaaaaaaaaaaaaaaaaaa  bbbbbbbbbbbbbbbb
```
```bash
echo -e "a,b\naaaaaaaaaaaaaaaaaaaaaaa,bbbbbbbbbbbbbbbb" | gum table -w 5,5
```
```
a      b
aaaa…  bbbb…
```
closes #285

fix(table): set widths

---

internal/stdin/stdin.go

we were trimming an ending \n, but it would then break a \r\n sequence, causing misrenders.
this fixes it
closes #682

fix(stdin): trim space instead of \n

---

spin/command.go
spin/spin.go

bubbletea by default will try to open a tty for stdin, this makes it not do that if we're not on a terminal (e.g. docker build)
on the same token, simplify rendering in that case, printing only the title ("Loading..." by default).
closes #328

fix(spin): if not a tty, only print title, do not open tty for stdin

---

table/command.go

this makes it automatically set `--print` if stdout is not a terminal, e.g., when piping into something else. 
Seems to me that this is what you would want anyway!

feat(table): set --print if stdout is not a terminal

---

choose/choose.go
choose/command.go
confirm/confirm.go
file/file.go
filter/command.go
filter/filter.go
gum.go
input/command.go
input/input.go
pager/pager.go
table/table.go
write/command.go
write/write.go

Some standards:
- Esc exits 1
- CTRL+C exits 130 (interrupt)
- Help arrows are always in HJKL order
closes #138

feat: esc exit 1, ctrl+c exit 130, help arrow order

---

confirm/command.go
confirm/confirm.go
confirm/options.go

Fixes nothing, this is a feature I found missing from a specific use case I had in mind.
Adds the `--show-output` flag to `gum confirm` which prints the prompt and the chosen action to STDOUT.
```shell
gum confirm --show-output 'Do you agree?'
gum confirm --show-output 'Do you agree?'
``` 
This merge adds 2 commits, only the first one (`4f9235b`) is required for the feature to work.
Since the feature doesn't affect `confirm/confirm.go` I feel like the second (`432182f`) isn't necessary, but I still included it in case I misunderstood the purpose of the model structure.

feat(confirm): add `--show-output`

---

filter/command.go
filter/options.go

feat(filter): allow to pre-select items with --selected

---

filter/command.go
internal/tty/tty.go

- currently, `--select-if-one` returns directly only if there is one option
- this pr changes it so it also returns if a `--value` is provided, and matching only gives 1 option, which is likely the expected behavior of that flag
- also made an internal tty package to handle printing results better
closes #311

feat(filter): --select-if-one returns if single match

---

choose/command.go
choose/options.go
filter/command.go
filter/options.go

allows to change how content from stdin is used, and how results are printed.
one could get around it piping into and from `tr`, but results aren't quite right, especially when `tr '\n' ','` for example, as it'll add an extra `,` in the end of the string.
This makes things a bit cleaner, hopefully.
closes #274

feat(choose,filter): --input-delimiter --output-delimiter

---

choose/command.go
choose/options.go
go.mod

I'm not sure if I like this impl, but it does work.
closes #406

feat(choose): label delimiters

---

choose/command.go
choose/options.go
filter/command.go
filter/options.go
format/command.go
format/options.go
input/command.go
input/options.go
internal/stdin/stdin.go
style/command.go
style/options.go
write/command.go
write/options.go

I think this would be mostly useful for choose and filter, but anyway, this allows to disable the ANSI stripping when reading from STDIN.
alternative implementation of #782

feat: --no-strip-ansi

---

confirm/command.go
internal/stdin/stdin.go

feat: yes|gum confirm

---

filter/command.go
filter/filter.go
filter/filter_test.go
go.mod
go.sum

Fixes https://github.com/charmbracelet/gum/issues/785
- it will fuzzy match against the stripped string 
- it will then render the styles string, taking ansi escape codes into account
- when a char matches, it'll use the matched style instead of whatever style the item had previously
- other chars will have their previous style though
- refactored the matches styling to do it in ranges instead of per char basis, as we now need to `ansi.Truncate`/`ansi.TruncateLeft` to avoid breaking styles
some screenshots:

fix(filter): properly handle options with ansi styles

---

default.nix
flake.lock

- changed src hash to make main branch build through nix 
- change version to 0.15.0
- update nix lock file to have go >= 1.23 instead of 1.22.2

chore(nix): update src hash and nix version

---

pager/pager.go

the height calculation was counting the empty line as well, which was incorrect.
this fixes the extra empty line in the bottom.

fix(viewport): remove extra line in viewport help

---

spin/spin.go

fix(spin): clear title after finished

---

table/command.go

Reverts charmbracelet/gum#762
see discussion in https://github.com/charmbracelet/gum/pull/806
closes #800  
closes #806

Revert "feat(table): set --print if stdout is not a terminal"

---

go.mod
pager/pager.go
pager/search.go

easily reproducible, especially with something like
```sh
PAGER="gum pager" man ls
```
Problems here were:
- reflow's truncate is not very efficient
- useless calls to truncate
- bad strings.Replace calls (not necessary, and wouldn't work if text has ansi sequences)
Fixes #823 
PS: this is better handled in #791, but that one is a bigger change (and depends on a /bubbles change as well), so I think we can probably do this instead for now and push a patch until #791 is done and merged.
---

fix(pager): memory/cpu usage when using soft-wrap

---

README.md

I am the maintainer of the FreeBSD port for gum.  Gum can now be installed natively in FreeBSD using either packages or ports.
- Add native installation instructions for FreeBSD.

Update FreeBSD installation instructions.

---

filter/options.go

Fixes #821 
Removes `'` from description, it also didn't match with the other description values

fix: generated completion invalid for fish shell

---

table/command.go
table/options.go
table/table.go

Fixes https://github.com/charmbracelet/gum/issues/196
This allow table display to be configurable and show item quantity on helper. It can be disabled by `hideIndicator`.

feat: show indicator on help keybindings (opt-in)

---

table/table.go

this prevents the help view from moving once you pass item 10 (or 100, or 1000, etc):

fix(table): padding on item indicator

---

completion/fish.go

Fixes #...
fix the following error on fish completion:
```
No matches for wildcard ''Options that should start as selected (selects all if given '*')''. See `help wildcards-globbing`.
complete -c gum -f -n '__fish_seen_subcommand_from filter' -x -l selected -d 'Options that should start as selected (selects all if given '*')'
```
-

fix wildcard escaping issue 

---

confirm/command.go

This is a quick fix to prove the point made here https://github.com/charmbracelet/gum/issues/876#issuecomment-2792207961 about the timeout condition not being handled properly at the moment

Detect timeout error and apply default option

---

main.go

Fixes #917 
fix logic to handle interrupt before timeout in error checking.
- Reorder conditions to check ErrInterrupted before ErrProgramKilled
- Prevents Ctrl+C from being incorrectly treated as timeout

fix: treating SIGINT(ctrl+c) as timeout.

---

choose/options.go

- :exclamation: **BREAKING CHANGE**: Rename environment variable `GUM_CCHOOSE_TIMEOUT` to `GUM_CHOOSE_TIMEOUT` 
This fixes the typo in the environment variable name.
Technically a breaking change because the old environment variable won't work anymore.
- Run `export GUM_CCHOOSE_TIMEOUT=1s`  
- Run `export GUM_CHOOSE_TIMEOUT=10s`  
- Run `gum choose 1 2 3` without this fix. It times out after 1 second.
- Run `gum choose 1 2 3` with this fix. It times out after 10 seconds.

fix(choose)!: Rename environment variable `GUM_CCHOOSE_TIMEOUT` to `GUM_CHOOSE_TIMEOUT`
