confirm/command.go
confirm/confirm.go
confirm/options.go

Fixes #31 
```
gum confirm --default=false
```

Confirmation Default

---

README.md

Signed-off-by: Carlos A Becker <caarlos0@users.noreply.github.com>

fix: demo in readme requires bash

---

completion/bash.go
completion/command.go
filter/command.go
format/command.go
format/options.go
input/command.go
internal/decode/align.go
internal/stdin/stdin.go
spin/command.go
spin/options.go
spin/spin.go
style/borders.go
style/spacing.go

Fixes #20 
* Adds `--show-output` flag to display output of command after spinning
* Exit code matches command's exit code

feat(spin): `--show-output` and exit code should match command's

---

examples/filter-key-value.sh

- wip
- docs: add filter example with identification (key / value)

Filter with Keys and hidden values

---

filter/command.go
filter/filter.go
internal/exit/exit.go
main.go

- feat: ctrl-c & esc abort filtering
- refactor: exit package

Abort filter when ctrl+c is pressed

---

.goreleaser.yml

Use our common package description.

fix: AUR package description

---

spin/command.go
spin/options.go
spin/spin.go

Pass stderr from the command run by gum spin analog to how stdout is passed.
This fixes #63.

feat: pass stderr

---

choose/choose.go

Fixes https://github.com/charmbracelet/gum/issues/82
- Fix page up logic

Fix paging up bug for `gum choose`

---

filter/command.go
filter/filter.go
filter/options.go

Fixes #86
- Add `--height` option for limiting `gum filter`
- Ability to scroll options (with viewport)

Filter --height and Scroll Viewport

---

spin/command.go

Fixes #94
- Change `gum spin` to run on `stderr`

Run `gum spin` on stderr

---

go.mod
go.sum

- `--char-limit` <= 0 should be ignored

Ignore write limit when non-positive

---

README.md

- Add `<picture>` and `<source>` for media

Resize Images Correctly on Mobile (web)

---

README.md

Pick a previously executed command from your shell history to execute, copy,
edit, etc...
```bash
gum filter < $HISTFILE --height 20
```
See visual feedback when entering password with masked characters with `gum
input --password`.
```bash
alias please='gum input --password | sudo --stdin'
```

Better Sudo + Shell History Picker examples

---

filter/filter.go

- Pre-allocate matches slice for memory performance

Pre-allocate fuzzy slice for performance

---

README.md
examples/skate.sh

- Add skate password manager + GIF
- Add `./examples/skate.sh` as a simple TUI for skate

docs: show usage with `skate`

---

choose/command.go
choose/options.go

Fixes #72
- `--selected` option to indicate what options that should start as selected

feat(choose): add --selected option to choose command

---

examples/diyfetch

😉 https://github.com/charmbracelet/gum/discussions/161#discussioncomment-3744601

Add DIYfetch to `examples/`

---

choose/command.go

Fixes #...
- 
- 
-
Added starting index to preselect the selected option when limit is one

feat(choose): Preselect the Selected Option When Limit is One

---

file/command.go
file/file.go
file/options.go

Highlight symlinks and display their resolved path.

feat(file): support symlinks

---

write/command.go
write/options.go
write/write.go

feat(write): use --header to display a label above the textarea

---

table/comma.csv
table/command.go

fix comma split bug in table

---

README.md

- Adds a little note to the README that describes how to run the flake with `file` as an example command.

added nix flake directions

---

file/file.go

Fixes #191 
- Allow gum file to follow symlink to directory

fix: symlink directory follows directory

---

choose/choose.go

feat(choose): use `tab` to toggle selection

---

file/command.go
file/file.go
file/options.go

Fixes #193 
- added `--file` flag for `file` command
- added `--directory` flag for `file` command

feat(file): allow separately file/dirs selection

---

go.mod
go.sum

Fixes #119
- Update bubbletea to v0.23.1
I tested and it does fix the windows issue. I'm not a go dev at all so feel free to edit it.
Thanks

fix: ✨ update bubbletea dependency

---

choose/choose.go

Fixes #251
- Add <kbd>ctrl+j</kbd> / <kbd>ctrl+k</kbd> to navigate choose menu

feat(choose): add ctrl+j / ctrl+k keybindings

---

input/command.go
input/input.go
input/options.go
write/write.go

Fixes #216
- Add `--header` and header styles flags for `gum input`.

feat(input): header values

---

file/file.go

Add support for going up/down a 'page' in `gum file`.
[![asciicast](https://asciinema.org/a/w7MT9F2w2IoFziusn7VxofUya.svg)](https://asciinema.org/a/w7MT9F2w2IoFziusn7VxofUya)

feat(file): Add page up/down key bindings

---

table/table.go

Fixes ##286
- Adds the escape-key to the switch-case, checking whether it should quit or not.

added esc-key to quit table

---

format/command.go
format/formats.go
format/options.go

Fixes #215
- Allow passing language to format code with in format code

Pass language to parse code with in format

---

file/command.go

some styles were not being set, for instance, the "no items" style
refs #343

fix: missing filepicker styles

---

input/command.go
input/input.go
input/options.go
write/command.go
write/options.go
write/write.go

Use `--width=0` for terminal width.

feat(write): width < 1 uses terminal width

---

format/options.go

Fixes #344
- Add `GUM_FORMAT_THEME` configuration option
- Add `GUM_FORMAT_LANGUAGE` configuration option

Add `GUM_FORMAT_THEME` / `GUM_FORMAT_LANGUAGE` env variables

---

internal/utils/utils.go
pager/command.go
pager/options.go
pager/pager.go
pager/search.go

feature: add pager search functionality

---

internal/utils/utils.go

Just a tiny doc comment correction.

fix(docs): correct LipglossPadding doc comment

---

pager/command.go
pager/options.go
pager/pager.go

Fixes #...
Timeout Parameter to Pager

feat: Adding timeout option to Pager command

---

filter/command.go
filter/filter.go
filter/options.go

Fixes #...
Using Timeout Option on Filter Command

feat: Adding timeout option to Filter command

---

input/command.go
input/input.go
input/options.go

Fixes #...
Timeout Feature for Input Command

feat: Timeout for Input Command

---

confirm/command.go
confirm/confirm.go
confirm/options.go

Fixes #...
Timeout for Confirm Command

feat: Timeout for Confirm Command

---

choose/choose.go
choose/command.go
choose/options.go

Fixes #...
Timeout for Choose Command

feat: Timeout for Choose Command

---

README.md

Following microsoft/winget-pkgs#111760, adds details on how to use WinGet to install Gum.

docs: Add WinGet installation details

---

log/command.go
log/options.go

Log predefined time formats

---

spin/spin.go

Streams stdout when piping in to not a tty.
This is useful for stdin forwarding while displaying a spinner:
```
gum spin --show-output -- curl http://parrot.live > log.txt
```

Gum Spin stdout streaming

---

filter/command.go
filter/options.go
input/command.go
input/options.go

Fixes #475
- Adds ability to change placeholder style.

Allow Placeholder Style Customization

---

format/formats.go

Format even when piped

---

.golangci-soft.yml
table/command.go

- unused is enabled on default config, but not on soft, fixed
- ifshort is deprecated
- fix actual lint issue

fix: lint issues, linter config

---

README.md

add documentation surrounding how to select multiple items in a list and returning them

docs(readme): add missing documentation

---

pager/pager.go

Fixes #541 
- Updated comment example from `gum page` to `gum pager` to reflect latest syntax

Update example in comment to latest pager syntax

---

main.go

Fixes #563 and fixes #588
- Adds if statement to check for error returned by `huh?`.

fix(main): handle huh user aborted error

---

input/command.go
write/command.go

Fixes #583
- Uncomments the code disabling the cursor style in input.
- Add the theme to `write`.

fix(input, write): re-enable cursor style

---

choose/command.go
go.mod
go.sum

* Added timeout option to choose and other patches (maybe)
-  Fixes #565 
- choose/command.go

Added timeout option to choose and other patches (maybe)

---

spin/spin.go

We need to pause the main tea.Program process to restore the terminal state before running the sub-process.
Fixes: https://github.com/charmbracelet/gum/issues/607

fix(spin): pause tea before running the sub-process

---

.github/workflows/goreleaser.yml
.github/workflows/nightly.yml

sign & notarize macos binaries on releases and nightlies

ci: sign & notarize macos binaries

---

filter/filter.go

Fixes #466 
- Adds cyclic navigation to easily transition between the first and last items.

feat(filter): Add cyclic navigation

---

filter/options.go
input/options.go
write/options.go

closes https://github.com/charmbracelet/gum/issues/586
it was a regression from previous stable

fix: use 0 as default width

---

style/options.go

closes #488
closes #492
not sure why this would be hidden...

fix: show background style help

---

.golangci-soft.yml
.golangci.yml
choose/command.go
filter/filter.go

fix: lint issues

---

go.mod
go.sum

refs #331
```console
$ du -hs gum-*
17M     gum-after
32M     gum-before
```

fix(deps): update goldmark-emoji

---

file/command.go
file/options.go

reworked the changes made in #495 
closes #495

feat(filepicker): show permissions and size

---

log/command.go
log/options.go

feat(log): support setting minimum log level with GUM_LOG_LEVEL

---

filter/command.go
filter/options.go

refs https://github.com/charmbracelet/gum/issues/676

fix: clarify filter --sort flag

---

pager/command.go
pager/options.go
pager/pager.go

use the help bubble in the pager component

fix(pager): use help bubble

---

table/command.go
table/options.go
table/table.go

feat(table): add help

---

table/command.go
table/options.go

As per [csv.Reader].
closes #345

feat(table): --lazy-quotes and --fields-per-record

---

table/command.go

fix(table): grow table rows based on --columns

---

choose/command.go
choose/options.go

feat(choose): --selected="*" to select all

---

file/command.go
file/file.go
file/options.go

feat(file): add --header

---

filter/command.go
filter/filter.go

feat(filter): ctrl+a to toggle select all

---

spin/command.go
spin/options.go
spin/spin.go

feat(spin): --show-stdout --show-stderr

---

go.mod
go.sum
gum.go
main.go
version/command.go
version/options.go

feat(version): adds command to check current gum version

---

choose/choose.go
filter/filter.go

- esc focus out of the filter
- esc with filter blurred quits
- g/G/j/k navigation when filter is blurred
closes #201

feat(filter): allow to focus out of filter

---

choose/command.go

refs https://github.com/charmbracelet/gum/issues/491
I'm not sure how useful this really is, though...

feat(choose): select from stdin

---

spin/command.go

fix: spin when not a tty

---

confirm/command.go

fix(confirm): do not print 'not confirmed' on exit 1

---

filter/filter.go
filter/filter_test.go
go.mod
go.sum

closes https://github.com/charmbracelet/gum/issues/785

fix(filter): wrong highlight when option has grapheme clusters

---

choose/options.go

fix: generated completion invalid for fish shell (choose/options)

---

table/command.go
table/options.go
table/table.go

Rename `HideIndicator` to `HideCount`

rename to `HideIndicator` to `HideCount` instead

---

default.nix

- changed src hash to make main branch build through nix 
- change version to 0.15.2

chore(nix): update version and vendor hash

---

choose/command.go

fix(choose): order when using --label-delimiter

---

filter/filter.go

fix(filter): text input width is too small
